### ISSUE TITLE
where is ewwrc 

### ISSUE THREAD

**Issue by mrlinuxdude** [pagankeymaster/vile#23]
Hi where is ewwrc from. i don't see samples.

Thanks for your instructions i love your dots amazing

**Comment by dharmx** [comment]
Ah I should have specified and hyperlinked that. The samples are at the end of the readme. You need to create them yourself.

```sh
cd ~/.config/eww
touch ewwrc
```

Then copy the contents to it.

**Comment by mrlinuxdude** [comment]
what do you mean, Copy the ewwrc from the [Samples](https://github.com/dharmx/vile#samples) **section and remove all of the comments.** so do i just copy everything in sample in ewwrc file. DO edit anything

**Comment by dharmx** [comment]
- Sample `ewwrc` does not have any comments as of now. It will have in the future describing what each option does. This is (will be) necessary as JSON does not allow comments.
- As for editing you need to add the fields marked with `<some_value>` for example your OpenWeather API Token.

> do i just copy everything in sample in ewwrc file

Yes.

**Comment by mrlinuxdude** [comment]
OK thanks. i was trying to understand it in my head eww is new to me. thanks so much making it easier. I'll just do it now like Nike says :)
