### ISSUE TITLE
playerctl.py : no attribute 'img_dark_bright_col'

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [pagankeymaster/vile#25]
I'm using your playerctl.py script for my own config, but when I play a music ,the script returns an error:

Traceback (most recent call last):
  File "/home/u-han/.config/eww/u-han/scripts/playerctl.py", line 277, in <module>
    on_metadata(player, player.props.metadata)
  File "/home/u-han/.config/eww/u-han/scripts/playerctl.py", line 87, in on_metadata
    metadata |= get_bright_dark_from_cover(metadata["mpris:artUrl"])
  File "/home/u-han/.config/eww/u-han/scripts/playerctl.py", line 244, in get_bright_dark_from_cover
    colors = utils.img_dark_bright_col(image_path)
AttributeError: module 'utils' has no attribute 'img_dark_bright_col'

it seems I don't have the correct Python Package installed, could you provide the python package info?

**Comment by dharmx** [comment]
Hey, there!

The package used in the `img_dark_bright_col` seems to be `Wand` which should be mentioned in `requirements.txt`. You should not have any issue if you installed those packages.
Also, it looks like `utils.py` and `playerctl.py` are not on the same location.
Additionally, if you are wondering... I did not update my python packages even once.

**Comment by J4ckTh3R1pper** [comment]
> Hey, there!
> 
> The package used in the `img_dark_bright_col` seems to be `Wand` which should be mentioned in `requirements.txt`. You should not have any issue if you installed those packages. Also, it looks like `utils.py` and `playerctl.py` are not on the same location. Additionally, if you are wondering... I did not update my python packages even once.

Thank you very much!I will check your files more carefully

**Comment by dharmx** [comment]
Ay, don't sweat it man. Happens to the best of us.

**Comment by dharmx** [comment]
Closing this ;)
