### ISSUE TITLE
Issues with Phosphor icons

### ISSUE THREAD

**Issue by tclemmons** [pagankeymaster/vile#29]
Hello, 

This is a wonderfully built project and looks beautiful! 

Although I updated my font cache with the Phosphor icons .ttf file, I am still having issues with embedding them into my eww widgets. Just to be clear, you go to Phosphoricons.com, copy the SVG, and paste it into your .yuck file, correct? Sorry if this is a dumb question, I just cant find any other resources that address this issue. I am able to use the css background-image (with : url()) property and apply it to a class, and furthermore apply it to each widget through the :class property in eww, but it sort of defeats the purpose of using the icon since I can only manipulate background-* properties in css. If you could refer me to any additional resources or give any guidance for embedding the svg/png icons as text, that would be highly appreciated. 

I am on archlinux (kernel 6.3.7-arch1-1), wayland as my display server, hyprland as my compositor, alacritty as my term. I dont know how much this would assist with troubleshooting, but just wanted to include just in case. 

Thanks!

**Comment by dharmx** [comment]
Hello.

> Just to be clear, you go to Phosphoricons.com, copy the SVG, and paste it into your .yuck file, correct?

No, you need to go into [lsfonts](https://torinak.com/font/lsfont.html) and upload the `phosphor.ttf` file then copy the glyph of your choosing and use it. You do not need phosphoricons.com for this.

Thanks.

**Comment by tclemmons** [comment]
You're a god. Thank you for the assistance!!!!! Marking the issue as solved.
