### ISSUE TITLE
The logger.py notification script does not work.

### ISSUE THREAD

**Issue by ItsTerm1n4l** [pagankeymaster/vile#32]
I am trying to make a eww notification panel but nearly every one uses your script, however when I try to run it with
`python logger.py init` i get this error
```
Traceback (most recent call last):
  File "/home/*****/.config/eww/scripts/logger.py", line 149, in <module>
    cache.Eavesdropper(master_callback, "/home/*****/.config/dunst").eavesdrop()
  File "/home/*****/.config/eww/scripts/cache.py", line 198, in eavesdrop
    bus.add_match_string(",".join([f"{key}={value}" for key, value in rules.items()]))
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 386, in add_match_string
    self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3.11/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.MatchRuleInvalid: Invalid match rule
```
(I have commented out my username)
What is going wrong and how do I fix it?
Thank you!

**Comment by dharmx** [comment]
Hello.

Very sorry for the delayed response. I haven't had the time to code anything for a few months. And, I have moved onto AwesomeWM. Anyways, from the looks of it, it seems that there have been changes to DBus APIs. I do not know what but for the time being you could try commenting the [`"eavesdrop": "true"`](https://github.com/dharmx/vile/blob/main/src/shell/cache.py#L196).

Sincerely,
dharmx

**Comment by ItsTerm1n4l** [comment]
After commenting out that line, i ran `python logger.py init` and then `python logger.py subscribe`, the `logger.py subscribe` command now outputs this `(box :class 'disclose-empty-box' :height 750 :orientation 'vertical' :space-evenly false (image :class 'disclose-empty-banner' :valign 'end' :vexpand true :path './assets/wedding-bells.png' :image-width 250 :image-height 250) (label :vexpand true :valign 'start' :wrap true :class 'disclose-empty-label' :text 'To fake it is to stand guard over emptiness. ── Arthur Herzog'))` which I assume is a sort of default placeholder, but when i do `notify-send hi` the output does not change.

**Comment by ItsTerm1n4l** [comment]
I am on wayland (hyprland) btw, in case that affects anything.

**Comment by dharmx** [comment]
Unfortunate. It seems that they have removed the eavesdropping feature. I am not aware if there are any alternatives. But, I see that `dbus-monitor interface='org.freedesktop.Notifications'` still works. So, there is a high chance that this is binding (<samp>dbus-python</samp>) specific.

**Comment by dharmx** [comment]
This might need a rework.

**Comment by ItsTerm1n4l** [comment]
This post https://stackoverflow.com/questions/46688576/custom-d-bus-monitor-written-in-python-not-receiving-all-messages looks like it might have the fix.

**Comment by dharmx** [comment]
Yes, that should work.

**Comment by dharmx** [comment]
Try using the newly created branch and let me know. It is crashing for me but you might have a different experience. (Could be because of AwesomeWM's notification daemon)

**Comment by ItsTerm1n4l** [comment]
Its gives no errors but `python ./logger.py subscribe` just shows 
```
(box :class 'disclose-empty-box' :height 750 :orientation 'vertical' :space-evenly false (image :class 'disclose-empty-banner' :valign 'end' :vexpand true :path './assets/wedding-bells.png' :image-width 250 :image-height 250) (label :vexpand true :valign 'start' :wrap true :class 'disclose-empty-label' :text 'To fake it is to stand guard over emptiness. ── Arthur Herzog'))
```
and when I run `notify-send hi` nothing changes in the `python ./logger.py subscribe` output and the `python ./logger.py init` command I have running in another terminal just stops with no feedback.

**Comment by ItsTerm1n4l** [comment]
I can do a screen recording of the whole process if u want?

**Comment by ItsTerm1n4l** [comment]
This is an incredibly basic eww notification manager I created from [these dotfiles](https://github.com/qxb3/gruvbox.hypr/tree/main). Unfortunately this method is only immediately compatible with dunst, however the shell script could easily be modified to work with mako at least, as I know that uses a very similar history format to dunst, so you could use this  workaround if your python script cannot be updated. 
This method just retrieves the dunst history and displays it using eww's `for` function.
**eww.yuck**
```
(deflisten v_notifs `./listennotif.sh`)
(defwindow notification
  :monitor "0"
  :stacking "overlay"
  :namespace "widget"
  :exclusive false
  :geometry (geometry
    :x "0%"
    :y "15px"
    :width "30%"
    :height "50%"
    :anchor "top right"
  )
(Notification)
)

(defwidget Notification []
(box
          :orientation "v"
          :space-evenly false
          :spacing 4
          :vexpand true

          (for notif in {v_notifs}
            (Notif
              :id {notif.id.data}
              :thumb {notif.icon_path.data}
              :title {notif.appname.data}
              :body {replace(notif.summary.data, "<[^>]*>", "")}
            )
          )
        )

)

(defwidget Notif [?thumb id title body]
  (box
    :class "notif card"
    :orientation "h"
    :space-evenly false
    :spacing 10
    :height 100
    :vexpand false
    :valign "start"

    (box
      :valign "start"
      :width 50
      :height 50

      (image
        :path thumb
        :image-width 50
        :image-height 50
        :halign "start"
        :valign "start"
      )
    )

    (box
      :class "meta"
      :orientation "v"
      :space-evenly false
      :spacing 4
      :valign "start"

      (label
        :class "title"
        :text title
        :wrap true
        :xalign 0
        :yalign 0
      )

      (label
        :class "body"
        :text body
        :xalign 0
        :yalign 0
        :wrap true
        :limit-width 100
      )
    )


    (box
      :halign "end"
      :hexpand true
      :space-evenly false
      :orientation "v"
      :valign "start"

      (eventbox :cursor "pointer"
        (button
          :class "x"
          :onclick "dunstctl history-rm ${id}"

          ""
        )
      )
    )
    )
    )
```
**listennotif.sh**
```
#!/bin/bash

while true; do
  notifs=`dunstctl history | jq -c -r '.data[0]'`
  echo $notifs

  sleep 1.5
done
```

**Comment by GabeDuarteM** [comment]
@dharmx I know its been some time, but wanted to let you know that I've been testing the fix pr with i3 and hyprland for a few months already and its been working great, in case you want to merge it :smile:
