### ISSUE TITLE
colors.sh missing

### ISSUE THREAD

**Issue by SakethKanchi** [pagankeymaster/vile#5]
While using the screen-lock. It says colors.sh is missing.
![image](https://user-images.githubusercontent.com/70198692/158013533-0d61e896-0b90-4603-a8e7-c7526a695b79.png)
Can you upload the colors.sh file?

**Comment by dharmx** [comment]
@SakethKanchi Ah I missed that somehow... it should be fixed now.
But, if you do need the `.colors.sh` file it can be found [here](https://github.com/pagankeymaster/nordfiles/blob/main/home/.colors.sh).
